### PR TITLE
Support use of different staking wallets

### PR DESCRIPTION
**Pull request by aguycalled**
This pull requests adds the option to have different staking wallets:

image

Added an option in settings to manage the nodes:

image

image

image

### CODE REVIEW

**Comment by aguycalled** [comment]
Modified wallet colours to make it look a bit more clean.

https://user-images.githubusercontent.com/24814046/162629327-c1facbdb-6ae4-4743-8df3-22e3a14b166b.mp4

**Comment by tsejerome** [comment]
1. I tried with the wallet @aguycalled gave me (`network testnet type next`), trying to transfer from n1JEU to private wallet but stuck at the progress spinner after clicking "send", the "confirm transaction" bottom tab doesn't appear. Also tried `navcash pool staking wallet`to `public` wallet, same thing happen.
2. For Balance Circle, should we make two green arcs instead of combining them, need slight refactoring for the component? Another hack is allowing more colors which wud be more annoying
image

**Comment by tsejerome** [comment]
I tried with public wallet transfer to private wallet with `network testnet type whisper`, and this error appears, probably an error with 
```
 read(walletName).then((password: string) => {
            createTransaction(
```
image

**Comment by aguycalled** [comment]
> I tried with public wallet transfer to private wallet with `network testnet type whisper`, and this error appears, probably an error with
> 
> ```
>  read(walletName).then((password: string) => {
>             createTransaction(
> ```
> 
> image

```
alex@alexs-MBP WhisperWallet % grep -r 'list[i].length' *
alex@alexs-MBP WhisperWallet % 
```

can't find references of that piece of code, can you show the stack trace?

**Comment by aguycalled** [comment]
> * I tried with the wallet @aguycalled gave me (`network testnet type next`), trying to transfer from n1JEU to private wallet but stuck at the progress spinner after clicking "send", the "confirm transaction" bottom tab doesn't appear. Also tried `navcash pool staking wallet`to `public` wallet, same thing happen.
> * For Balance Circle, should we make two green arcs instead of combining them, need slight refactoring for the component? Another hack is allowing more colors which wud be more annoying

* should be fixed in https://github.com/aguycalled/WhisperWallet/pull/50/commits/4faaafd2f7615b0bd1be1ce3f1fe7071380b62d6
* not sure about making two arcs, I think we can keep one arc for the whole staking balance

**Comment by tsejerome** [comment]
for error `undefined is not an object (evaluating 'list[i].length')`
Steps to reproduce:
1. use network testnet type whisper
2. Wait till all balance are loaded first
3. Click Public Wallet --> move to other wallet
4. Choose Private and the amount as 0.2 (Public wallet shd have 1.9 nav)
5. click send and the error of `undefined is not an object (evaluating 'list[i].length')` will appear.
image

It happens at `createTransaction` function, .catch returns a type of Error so we shd use e.message/e.name/e.stack instead of e.trace
image

**Comment by aguycalled** [comment]
> for error `undefined is not an object (evaluating 'list[i].length')` Steps to reproduce:
> 
> 1. use network testnet type whisper
> 2. Wait till all balance are loaded first
> 3. Click Public Wallet --> move to other wallet
> 4. Choose Private and the amount as 0.2 (Public wallet shd have 1.9 nav)
> 5. click send and the error of `undefined is not an object (evaluating 'list[i].length')` will appear.
>    image
> 
> It happens at `createTransaction` function, .catch returns a type of Error so we shd use e.message/e.name/e.stack instead of e.trace

worked for me:

image

**Pull request merged**
