### PR TITLE
Feature/splash screen

### PR DESCRIPTION
**Pull request by tsejerome**

### CODE REVIEW

**Comment by aguycalled** [comment]
tested and worked for iOS 15

**Comment by aguycalled** [comment]
seeing this error in android:

```
BUILD SUCCESSFUL in 17s
505 actionable tasks: 8 executed, 497 up-to-date
info Connecting to the development server...
8081
info Starting the app on "emulator-5554"...
Starting: Intent { cmp=com.navcash/.MainActivity }
Error type 3
Error: Activity class {com.navcash/com.navcash.MainActivity} does not exist.
```

**Comment by tsejerome** [comment]
When I run`npx react-native run-android`, I got:
```
BUILD SUCCESSFUL in 6m 6s
505 actionable tasks: 487 executed, 18 up-to-date
info Connecting to the development server...
info Starting the app on "emulator-5554"...
Starting: Intent { cmp=com.navcash/.MainActivity }
```

**Comment by aguycalled** [comment]
tried some of the things there already but i will try some that i havent

**Comment by aguycalled** [comment]
> When I run`npx react-native run-android`, I got:
> 
> ```
> BUILD SUCCESSFUL in 6m 6s
> 505 actionable tasks: 487 executed, 18 up-to-date
> info Connecting to the development server...
> info Starting the app on "emulator-5554"...
> Starting: Intent { cmp=com.navcash/.MainActivity }
> ```
> 
> I think it might be caching issue and here is a possible fix: https://stackoverflow.com/a/36521856

tried what said in this post and still seeing this issue

**Comment by aguycalled** [comment]
> > When I run`npx react-native run-android`, I got:
> > ```
> > BUILD SUCCESSFUL in 6m 6s
> > 505 actionable tasks: 487 executed, 18 up-to-date
> > info Connecting to the development server...
> > info Starting the app on "emulator-5554"...
> > Starting: Intent { cmp=com.navcash/.MainActivity }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I think it might be caching issue and here is a possible fix: https://stackoverflow.com/a/36521856
> 
> tried what said in this post and still seeing this issue

Fixed it removing `android/.gradle` and running `npx react-native run-android -variant=release`

For `debug`, it happened the app was indeed installed on the emulator but not launched. So I could launch it manually.

Will test this PR soon.

**Comment by tsejerome** [comment]
Shd I set the splash screen to be enabled only in release natively at MainActivity?

**Pull request merged**
