### PR TITLE
Fix/circle animation

### LINKED ISSUE #7: Segment circle showing balance does not close
When there is only one type of balance, the segment circle does not close to create a full circle.

image

### PR DESCRIPTION
**Pull request by tsejerome**
Resolves #7 and #8

### CODE REVIEW

**Comment by aguycalled** [comment]
image

**Comment by aguycalled** [comment]
image
image

gap between segments is not constant while being animated

**Comment by aguycalled** [comment]
the transition between showing the sync progress and balances is not smooth. there circle disappears for some seconds, and shows some intermediate state in between

**Comment by aguycalled** [comment]
image

the initial gap is bigger than the other gaps, and is not aligned in the center but shifted to the left

**Comment by aguycalled** [comment]
I've also noticed that the segments are thicker than before

**Comment by aguycalled** [comment]
when using `yarn` to install the packages, there must be some dependency missing, because bitcore-lib does not have BigInt support and public nav transactions do not work.

when doing `npm i` I see the following error:

```
alex@alexs-MacBook-Pro WhisperWallet % npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: WhisperWallet@0.0.1
npm ERR! Found: react-native-reanimated@2.5.0
npm ERR! node_modules/react-native-reanimated
npm ERR!   react-native-reanimated@"^2.3.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react-native-reanimated@"^1.4.0" from @callstack/reanimated-arc@0.1.0-alpha.3
npm ERR! node_modules/@callstack/reanimated-arc
npm ERR!   @callstack/reanimated-arc@"^0.1.0-alpha.3" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/alex/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/alex/.npm/_logs/2022-03-25T12_13_51_973Z-debug-0.log
```

when doing `npm i --force` everything works (public nav txs too), but I think it is not a clean solution

**Comment by tsejerome** [comment]
As per requested, will look into:
- flashing issue (intentionally designed but will find workaround)
- non constant gap between arcs
- key warning issue

Segments width shd be the same as before as I use the same variable, but I can set it to be thinner
Dependencies issue, I will also see if can solve it

**Comment by tsejerome** [comment]
✅ Fixed initial gap issue, was affected by the original code of setting `totalArcSize={353}`
✅ Adjusted segment thickness (if you wanna change it just change `arcWidth` at the defaultProps)
✅ Package clashing issue
✅ Flashing Issue
✅ Non constant gap between arcs
✅ Child key issue

**Comment by aguycalled** [comment]
- the initial gap does not look centered yet

image

- the animation when the balance segments are first shown looks a bit off. maybe you can see it better if you load a wallet with balance (shared a mnemonic on telegram) or with this video:

https://user-images.githubusercontent.com/24814046/160279857-86f66bea-8b48-407e-b752-966ad989fbcc.mp4

**Comment by tsejerome** [comment]
Sure, will update accordingly. I designed it that way bcoz initially I saw `initialRotation` seems to be 210, `minArcSpacing` and `minArcSpacing` were initially 14 too.

**Comment by tsejerome** [comment]
Modified according to @aguycalled review, please check the last few seconds of the video:

https://user-images.githubusercontent.com/20391660/160334821-e6359a13-8eab-404f-859e-ca3865ccee38.mp4

**Comment by aguycalled** [comment]
I've added a new connection state in [a0c9978](https://github.com/aguycalled/WhisperWallet/pull/29/commits/a0c99786b127f0fd0238b08b63bad0a85392f097), `Connection_Stats_Enum.Syncing`.

I think the logic should be:

- `connected == Connection_Stats_Enum.Syncing`: Show the SegmentCircle with the sync progress

- `connected == Connection_Stats_Enum.Connecting`: Show the SegmentCircle with the infinite load animation and "Connecting" in the middle of the circle

- `connected == Connection_Stats_Enum.Connected`: Show the SegmentCircle with the balances

A possible solution for the balances changing while the wallet synchronises (which can confuse the user), could be to hide the balance section when the first sync hasn't completed in a layout like this:

image

When tapping the bottom triangle, then the `AccountTabs` would be shown, skipping having to wait until sync is finished. I don't know if some descriptive text would be needed below the triangle (Tap to hide or something like that, I'd let you decide). Ideally the transition between layouts should be animated and smooth.

I've added `firstSyncCompleted` to the `WalletProvider` so the wallet can detect whether the first sync has completed or not. So this layout should be used when `firstSyncCompleted == false && (connected == Connection_Stats_Enum.Connecting || connected == Connection_Stats_Enum.Syncing)`

**Pull request merged**
