### PR TITLE
Add option to resync wallet when opening

### LINKED ISSUE #9: Add option to resync a wallet when opening
Add an option in the `Open Wallet` section to choose whether to clear the transaction history and resync or not.

This is accomplished by setting `zapwallettxes` to `true|false` in the function `createWallet` from the `WalletProvider`.

### PR DESCRIPTION
**Pull request by aguycalled**
Fixes #9

### CODE REVIEW

**Comment by aguycalled** [comment]
https://user-images.githubusercontent.com/24814046/162291437-99cab669-7325-4bd1-9678-263be675a4a5.mp4

**Comment by aguycalled** [comment]
maybe I will change the layout and use a bottomTab instead

**Comment by tsejerome** [comment]
Just add a button at the bottom is fine

**Comment by tsejerome** [comment]
Thinking whether we shd move this to the settings pages

**Pull request closed without merging**
